/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package collectionsjava;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("hello!");
        return true;
    }
}
